#!/usr/bin/env bash

info() {
    echo "[I] $1"
}

. ./env $2

MANIFESTS_PATH=$(realpath $SMARTBOX_PATH/cluster/manifests)

info "Deleting manifests"
kubectl delete -f $MANIFESTS_PATH/$definition.yaml

info "Stopping Kubernetes"
vagrant suspend
