#!/usr/bin/env bash

. utils.sh

ACTION="kubectl"
ARGS=""
SSH_OPTS="-qt -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -A"

while [[ $# > 0 ]] ; do
    case $1 in
        -c|--cluster-name)
            CLUSTER="$2"
            shift
            ;;
        -s|--ssh)
            ACTION="ssh"
            ;;
        *)
            ARGS+="$1 "
            ;;
    esac
    shift
done

do_kubectl() {
     do_ssh sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf "$ARGS"
}

do_ssh() {
    ssh-add key/id_rsa &> /dev/null
    if [ "$(host)" = "localhost" ]; then
        ssh $SSH_OPTS ubuntu@$(master_ip) "$@"
    else
        ssh $SSH_OPTS $(host) ssh $SSH_OPTS ubuntu@$(master_ip) "$@"
    fi
}

case $ACTION in
    "kubectl")
        do_kubectl
        ;;
    "ssh")
        do_ssh
        ;;
    *)
        fatal "unknown action: $ACTION"
        ;;
esac
