#!/usr/bin/env bash

. utils.sh

ACTION="kubectl"
ARGS=""
SSH_LOCAL_OPTS="-t -q -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -A"
SSH_OPTS="-i key/id_rsa $SSH_LOCAL_OPTS"

while [[ $# > 0 ]] ; do
    case $1 in
        -a|--all)
            ACTION="all"
            ;;
        -c|--cluster-name)
            CLUSTER="$2"
            shift
            ;;
        -s|--ssh)
            ACTION="ssh"
            ;;
        *)
            ARGS+="$1 "
            ;;
    esac
    shift
done

do_all() {
    ARGS="get all --all-namespaces"
    do_kubectl
}

do_kubectl() {
    do_ssh sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf "$ARGS"
}

do_ssh() {
    chmod 600 key/id_rsa &> /dev/null
    if [ "$(host)" = "localhost" ]; then
        ssh $SSH_OPTS ubuntu@$(master_ip) "$@"
    else
        ssh-add key/id_rsa &> /dev/null
        ssh $SSH_LOCAL_OPTS $(host) ssh $SSH_LOCAL_OPTS ubuntu@$(master_ip) "$@"
    fi
}

case $ACTION in
    "all")
        do_all
        ;;
    "kubectl")
        do_kubectl
        ;;
    "ssh")
        do_ssh
        ;;
    *)
        fatal "unknown action: $ACTION"
        ;;
esac
