#!/usr/bin/env bash

fatal() {
    echo "$1; quitting"
    exit 1
}

info() {
    echo "[I] $1"
}

. ./env $2

SMARTBOX_PATH=$(realpath ${1:-..})
MANIFESTS_PATH=$(realpath $SMARTBOX_PATH/cluster/manifests)

DEFAULT_INTERFACE=$(awk '$2 == 00000000 { print $1 }' /proc/net/route)
DEFAULT_INTERFACE_IP=$(ip addr show $DEFAULT_INTERFACE | awk '$1 == "inet" {print $2}' | cut -f1 -d/)

info "Requesting sudo"
sudo -v

info "Starting Kubernetes"
minikube start --vm-driver=kvm

info "SMARTBOX_PATH: $SMARTBOX_PATH"
info "KUBECONFIG: $KUBECONFIG"

info "Loading kernel module"
sudo modprobe nfsd || fatal "could not load nfs kernel module -- NFS exports won't work"

info "Starting NFS server"
docker run -d -v $SMARTBOX_PATH:$SMARTBOX_PATH --network=host --name smartbox-dev-nfs --privileged cpuguy83/nfs-server $SMARTBOX_PATH &> /dev/null

info "Creating k8s persistent volume"
sed "s/NFS_SERVER_IP_ADDRESS/$DEFAULT_INTERFACE_IP/" manifests/pv.yaml | kubectl apply -f -

info "Creating k8s persistent volume claim"
kubectl apply -f manifests/pvc.yaml

for definition in brain-config cell-config; do
    info "Creating $definition"
    kubectl apply -f $MANIFESTS_PATH/$definition.yaml
done

info "Updating brain-config"
kubectl apply -f manifests/brain-config.yaml

info "Updating cell-config"
kubectl apply -f manifests/cell-config.yaml

for definition in mysql mongodb redis brain-secrets cell-secrets brain cell; do
    info "Creating $definition"
    kubectl apply -f $MANIFESTS_PATH/$definition.yaml
done
