apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-config
data:
  rails.env: development
  nginx.ingress.conf: |
    upstream cell {
      server unix:///run/cell/cell.sock;
    }
    server {
      listen 80;
      keepalive_timeout 5;
      location / {
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header Host              $http_host;
        proxy_redirect                     off;
        proxy_pass                         http://cell;
      }
    }
